### ISSUE TITLE
Peminjaman dan pengembalian tidak berjalan

### ISSUE THREAD

**Issue by Muhammad-Ikhwan-Fathulloh** [silvianurb/Tugas_WP2_Pertemuan5#1]
Peminjaman dan pengembalian tidak berjalan, tidak ada button untuk melakukan aksi tersebut, silahkan perbaiki.

**Comment by silvianurb** [comment]
izin konfirmasi pa, project uts silvia sudah diperbaiki jadi ada fungsi peminjaman dan pengembalian. terima kasih pa mohon maaf atas kekeliruannya

**Comment by silvianurb** [comment]
> Peminjaman dan pengembalian tidak berjalan, tidak ada button untuk melakukan aksi tersebut, silahkan perbaiki.
izin konfirmasi pa, project uts silvia sudah diperbaiki jadi ada fungsi peminjaman dan pengembalian. terima kasih pa mohon maaf atas kekeliruannya

**Comment by Muhammad-Ikhwan-Fathulloh** [comment]
Ok sip
